apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-stack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-stack
    app.kubernetes.io/part-of: devfile-go-stack
  name: devfile-go-stack
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: devfile-go-stack
status:
  loadBalancer: {}
